### PR TITLE
Hello

### PR DESCRIPTION
**Pull request by wfogame**
sad

### CODE REVIEW

**Comment by dinguschan-owo** [comment]
@wfogame what exactly is this? like what did you add

**Comment by Fortato** [comment]
@dinguschan-owo idk what this guy was trying to do, he changed all your credits to himself and deleted a ton of stuff, the first commit also added a new script that looks like it might create a new about blank tab? not sure if it works though

**Comment by dinguschan-owo** [comment]
> @dinguschan-owo idk what this guy was trying to do, he changed all your credits to himself and deleted a ton of stuff, the first commit also added a new script that looks like it might create a new about blank tab? not sure if it works though. wait the last commit just changes the credits back to you and the one before removes the about:blank creator?

Yeah dude I just took a close look after reading you comment, and I think your right. The scrip just like doesn't work, and idk about the credits but I'm gonna see if he responds to explain before I close this.

**Comment by dinguschan-owo** [comment]
yeqh, no.

**Pull request closed without merging**
