### PR TITLE
🤓☝

### PR DESCRIPTION
**Pull request by STPv22**

### CODE REVIEW

**Comment by STPv22** [comment]
alr. lmao

**Comment by STPv22** [comment]
would you consider rewriting this in ts? over 1000 line of code is a lot to go through.

**Comment by dinguschan-owo** [comment]
Yeah totally, your completely right

**Comment by dinguschan-owo** [comment]
alright so it just occcered to me i barley know typescript. uhm

**Comment by STPv22** [comment]
it honesly mostly the same I think

**Comment by dinguschan-owo** [comment]
yeah its close, but may I ask why you want it in typescript

**Comment by STPv22** [comment]
the script.js file is over 1000 lines long. it would make adding to the project much easier

**Comment by dinguschan-owo** [comment]
I see your point, but I am not experienced with typescript, and I did markup the js with tonnes of comments. Im afraid it would just take too long for me to learn ts even with my exisitng js knowlege, but if you know how to I would totally mergei t

**Comment by STPv22** [comment]
ok.

**Comment by dinguschan-owo** [comment]
sorry dude but i just dotn knwo typescript

**Comment by STPv22** [comment]
bro its almost exactly the same. you seem to know js pretty well. Ill set it up tonight or tomorrow.

**Comment by STPv22** [comment]
you can potentially just copy paste most of the code

**Pull request closed without merging**
